---
title: "git_01"
author: "Marium Khanum"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

How doth the little crocodile  
Improve his shining tail  
And pour the waters of the Nile  
On every golden scale!  
How cheerfully he seems to grin  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Snow falling and night falling fast, oh, fast  
In a field I looked into going past,  
And the ground almost covered smooth in snow,  
But a few weeds and stubble showing last.  
The woods around it have it--it is theirs.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had no business to be there  
After the day was done--  
'It's very rude of him,' she said,  
'To come and spoil the fun!'  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

When you are old and grey and full of sleep,  
And nodding by the fire, take down this book,  
And slowly read, and dream of the soft look  
Your eyes had once, and of their shadows deep;  
  
How many loved your moments of glad grace,  
And loved your beauty with love false or true,  
But one man loved the pilgrim soul in you,  
And loved the sorrows of your changing face;  
  
And bending down beside the glowing bars,  
Murmur, a little sadly, how Love fled  
And paced upon the mountains overhead  
And hid his face amid a crowd of stars.  